### ISSUE TITLE
Home + Học bạ

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock_Hackathon#4]
Có sử dụng thư viện UI của React nên cần thì hỏi Tú (@tunbk1002).

Làm giao diện trước rồi thì hỏi Tú (@tunbk1002) gắn cái API vào.

**Comment by HSGamer** [comment]
Deadline: 24/08/2022 theo như lần họp này

**Comment by khoatvbattu** [comment]
@HSGamer giúp tui gắn cái API vào test trang Học Bạ với, bên branch "Home+SchoolReport" á, bên đây do lỗi setup nên chạy k được
